module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },
  TEACHER_MODAL_BODY_TYPES: {
    TEACHER_DETAIL: "TEACHER_DETAIL",
    TEACHER_ADD_NEW: "TEACHER_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },
  PUPIL_MODAL_BODY_TYPES: {
    PUPIL_DETAIL: "PUPIL_DETAIL",
    PUPIL_ADD_NEW: "PUPIL_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },
  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
    FILTER: "FILTER",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
    PUPIL_DELETE: "LEAD_DELETE",
    TEACHER_DELETE: "LEAD_DELETE",
  },
});
