module.exports = Object.freeze({
  TEACHER_INITIAL_STATE: {
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    age: "",
    location: "",
    pasport: "",
    subject: "",
  },
  PUPIL_INITIAL_STATE: {
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    homePhone: "",
    age: "",
    location: "",
    pasport: "",
    subject: "",
    cupon: "",
    gender: "male",
    teacher: "",
    course: "",
  },
  COURSE_INITIAL_STATE: {
    teacher: [],
    pupil: [],
    type: "",
    name: "",
    cost: "",
    time: "",
    pupilQuantity: "11",
    isAktive: true,
  },
  FEE_INITIAL_STATE: {
    firstName: "",
    lastName: "",
    startDate: "",
    endDate: "",
    pasport: "",
  },
    GES_INITIAL_STATE: {
    name: "",
    region: "",
    status: "",
    repair: "",
    power: "",
    age: "",
    agregate: "",
    pasport: "",
    subject: "",
    cupon: "",
    gender: "male",
    teacher: "",
    course: "",
  },
    AGGREGATES_INITIAL_STATE: {
    hydroTurbine: {
    model: "",
    power: null,
    efficiency: null,
    serialNumber: "",
    year: null,
  },

  hydroGenerator: {
    model: "",
    power: null,
    voltage_V: null,
    cosphi: null,
    efficiency: null,
    serialNumber: "",
    year: null,
  },

  transformer: {
    type: "",
    power: null,
    primary_kV: null,
    secondary_kV: null,
    efficiency: null,
    cooling: "",
    serialNumber: "",
    year: null,
  },

  },
});
